---
- name: Fail when invalid parameters
  fail:
    msg: "You must either specify qcow_url or glance_image"
  when: "glance_image is defined and qcow_url is defined"

- name: Glance image upload
  include_tasks: "glance_image.yml"
  when: glance_image is defined

- name: Qcow2 image upload
  include_tasks: "qcow2_image.yml"
  when: qcow_url is defined

- name: Import external image
  include_tasks: "create_vm_template_image.yml"
  when: kvm_import is defined or xen_import is defined or vmware_import is defined
